<a href="https://colab.research.google.com/github/Mukils03/Data-science-/blob/main/Numpy_task.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
#import Numpy library
import numpy as np

In [ ]:
a=np.array([1,2,3])       #create one dimentional array
b=np.array([4,5,6])       #create two dimentional array
c=np.array([97,98,99])   #create three dimentional arrays
print(np. concatenate([a, b]))#CONCADENATE 2 ARRAYS
np. concatenate([a, b, c]) #CONCADENATE  3 ARRAYS

[1 2 3 4 5 6]


array([ 1,  2,  3,  4,  5,  6, 97, 98, 99])

In [ ]:
import numpy as np
a = np.array([5,10,15])  #create one dimentional array
print(a)

[ 5 10 15]


In [ ]:
import numpy as np
b = np.array([(9,8,7), (4,5,6)], dtype = int)          #create two dimentional arrays
print(b)

[[9 8 7]
 [4 5 6]]


In [ ]:
import numpy as np
b = np.array([(9,8,7), (4,5,6)], dtype = int)          #create two dimentional arrays
print(b)

[[9 8 7]
 [4 5 6]]


In [ ]:
import numpy as np
c = np.array([[(1.5,2.5,3.5), (4.5,5.5,6.5)], [(7.5,8.5,9.5), (10.5,11.5,12.5)]],dtype = float)       #create three dimentional arrays
print(c)

[[[ 1.5  2.5  3.5]
  [ 4.5  5.5  6.5]]

 [[ 7.5  8.5  9.5]
  [10.5 11.5 12.5]]]


In [ ]:
import numpy as np
np.zeros((3,3))     #create zerows of array

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [ ]:
import numpy as np
np.ones((2,4),dtype=np.int16)      #create ones of arrays

array([[1, 1, 1, 1],
       [1, 1, 1, 1]], dtype=int16)

In [ ]:
x5=[1,2,3,4,5,6,7,8,9]
p, q, r=np.split(x5, [3, 6])     #spilt the array
print(p, q, r)

[1 2 3] [4 5 6] [7 8 9]


In [ ]:
grid=np.arange(16). reshape((4, 4))   #reshape the array
upper, lower = np.vsplit(grid,[2])
left, right=np.hsplit(grid, [2])
print(upper)
print(lower)
print(left)
print(right)

[[0 1 2 3]
 [4 5 6 7]]
[[ 8  9 10 11]
 [12 13 14 15]]
[[ 0  1]
 [ 4  5]
 [ 8  9]
 [12 13]]
[[ 2  3]
 [ 6  7]
 [10 11]
 [14 15]]


In [ ]:
x=np.arange(20)  #arange element below 20
print(x)
print(x[15: 18])
print(x[1: 10])
print(x[5:: 3])
print(x[ :: -8])

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19]
[15 16 17]
[1 2 3 4 5 6 7 8 9]
[ 5  8 11 14 17]
[19 11  3]


In [ ]:
import numpy as np
np.random.seed(0)
x2 = np.random.randint(30, size=(3, 3))  #random element below 30
print(x2)

[[12 15 21]
 [ 0  3 27]
 [ 3  7  9]]


In [ ]:
import numpy as np
d = np.arange(10,20,2)  #create an array 10 to 20 the range of 2
print(d)

[10 12 14 16 18]


In [ ]:
import numpy as np
e = np.full((2,2),7)  #fill the perticular element in full array
print(e)

[[7 7]
 [7 7]]


In [ ]:
import numpy as np
a=np.empty((3,2))   #create an empty array
print(a)

[[4.4e-323 4.0e-323]
 [3.5e-323 2.0e-323]
 [2.5e-323 3.0e-323]]


In [ ]:
import numpy as np
np.random.seed(0)
x3 = np.random.randint(50, size=(1,2,3))
print("x3 ndim:", x3. ndim)     #dimention of an array
print("x3 shape:", x3. shape)     #shape of an array
print("x3 size:" , x3. size)     #size of an array
print("x3 dtype:", x3. dtype)     #data type of an array
print("itemsize:", x3.itemsize, "bytes")
print("nbytes:", x3.nbytes, "bytes")

x3 ndim: 3
x3 shape: (1, 2, 3)
x3 size: 6
x3 dtype: int64
itemsize: 8 bytes
nbytes: 48 bytes


In [ ]:
import numpy as np
np.random.random((2,2))  #random element

array([[0.4236548 , 0.64589411],
       [0.43758721, 0.891773  ]])

In [ ]:
import numpy as np
np.linspace(5,50,2)

array([ 5., 50.])

In [ ]:
import numpy as np
np.linspace(5,50,2)

array([ 5., 50.])

In [ ]:
import numpy as np
np.random.seed(0)
x3 = np.random.randint(40, size=(3, 3, 3))
print(x3)

[[[ 0  3  3]
  [39  9 19]
  [21 36 23]]

 [[ 6 24 24]
  [12  1 38]
  [39 23 24]]

 [[17 37 25]
  [13  8  9]
  [20 16  5]]]


In [ ]:
import numpy as np
np.random.seed(0)
x3 = np.random.randint(40, size=(3, 3, 3))
print(x3)

[[[ 0  3  3]
  [39  9 19]
  [21 36 23]]

 [[ 6 24 24]
  [12  1 38]
  [39 23 24]]

 [[17 37 25]
  [13  8  9]
  [20 16  5]]]


In [ ]:
print("sin is",np.sin(a) )  #sin of an array
print("cos is",np.cos(a) )  #cos of an array
print("tan is",np.tan(a) )  #tan of an array

sin is [[4.4e-323 4.0e-323]
 [3.5e-323 2.0e-323]
 [2.5e-323 3.0e-323]]
cos is [[1. 1.]
 [1. 1.]
 [1. 1.]]
tan is [[4.4e-323 4.0e-323]
 [3.5e-323 2.0e-323]
 [2.5e-323 3.0e-323]]


In [ ]:
print(np.arcsin(a) )    #arcsin of an array
print(np.arccos(a) )    #arccos of an array
print(np.arctan(a) )  #arctan of an array

[[4.4e-323 4.0e-323]
 [3.5e-323 2.0e-323]
 [2.5e-323 3.0e-323]]
[[1.57079633 1.57079633]
 [1.57079633 1.57079633]
 [1.57079633 1.57079633]]
[[4.4e-323 4.0e-323]
 [3.5e-323 2.0e-323]
 [2.5e-323 3.0e-323]]


In [ ]:
print(np.random.rand())
print(np.random.randn())
print(np.random.randint(5))
print(np.random.shuffle([4,8,12,15]))

0.7781567509498505
-0.18158257273119596
3
None


In [ ]:
import numpy as np
f = np.array([(9,8,7), (4,5,6)], dtype = int)
g = np.array([(1,2,3), (3,5,8)], dtype = int)
print(np.add(f,g))  #add the array element
print(np.subtract(f,g)  )#subtract the array element
print(np.multiply(f,g))  #multiply the array element
print(np.divide(f,g))  #divide the array element

[[10 10 10]
 [ 7 10 14]]
[[ 8  6  4]
 [ 1  0 -2]]
[[ 9 16 21]
 [12 25 48]]
[[9.         4.         2.33333333]
 [1.33333333 1.         0.75      ]]
